### ISSUE TITLE
Possibility of Adding Clock Example?

### ISSUE THREAD

**Issue by AlexLandherr** [bitbank2/MAX7219#1]
Hi, I'm wondering whether it's possible to add a clock example for this library?

I'm just learning C++ and have this example of getting the current UTC time as a std::string:
```
std::string UTC_string() {
    //Return UTC time as a std:.string with format "yyyy-mm-dd hh:mm:ss".
    std::time_t time = std::time({});
    char timeString[std::size("yyyy-mm-dd hh:mm:ss UTC")];
    std::strftime(std::data(timeString), std::size(timeString), "%F %T UTC", std::gmtime(&time));
    return timeString;
}
```

I know this can't be printed to the 7-segment displays that use the MAX7219, if you are willing to add a clock example could you modify it to work with 2 7-segment displays chained together?

**Comment by bitbank2** [comment]
The example in the repo basically does what you want. I'm not really sure what you're asking.
To use a C++ String class (std::string) with my code, just get the C string pointer from it (mystring.c_str()).
