### ISSUE TITLE
Use of different font size such as 5x7 or 4x7 in led matrix.

### ISSUE THREAD

**Issue by mhanuel26** [bitbank2/MAX7219#2]
Hi @bitbank2  Larry, 

I am using your library and I was looking to use a smaller font. I understand some of the logic to generate the font array, but it looks there are a few ways to express it and I believe it is highly couple with the decoding set for max7219 in your code  so I know your code will need some modifications.

Can you let me know in first place how do you generate the 6x8 font array for instance?

I found this tool [online ](https://dotmatrixtool.com/)with [sources ](https://github.com/stefangordon/dotmatrixtool)available which looks nice, a bit of manual work to generate the 128 bytes for ascii table anyway. 

I will appreciate your comments,
Manuel

**Comment by bitbank2** [comment]
I had the font data from projects over the last 30 years. I honestly don't know where I got it originally.
